version: '3'

services:
  elasticsearch:
    image: library/elasticsearch:6.5.4
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200

  kibana:
    image: library/kibana:6.5.4
    container_name: kibana
    restart: always
    ports:
      - 5601:5601

  curator:
    image: eldersoss/curator-docker
    restart: always
    command: "--host elasticsearch --port 9200 delete indices --older-than 1 --timestring '%Y.%m.%d' --time-unit days"

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch

  dependencies:
    image: openzipkin/zipkin-dependencies
    restart: always
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
    depends_on:
      - elasticsearch